#!/usr/bin/env python3
"""
Generate family entries for color_ordering.tsv grouped by order.
This is a one-off script to generate the ordering, not part of the workflow.

Usage:
    python3 scripts/generate_family_colors.py

This will append family entries to defaults/color_ordering.tsv
"""

import pandas as pd
import sys
from pathlib import Path

def get_family_order_data():
    """Find and read metadata to extract family-order combinations."""

    # Try different possible metadata locations
    possible_paths = [
        Path("results/metadata.tsv"),
        Path("../ingest/results/metadata.tsv"),
        Path("../ingest/data/metadata.tsv"),
        Path("data/metadata.tsv"),
    ]

    metadata_path = None
    for path in possible_paths:
        if path.exists():
            metadata_path = path
            print(f"Found metadata at: {path}")
            break

    if not metadata_path:
        print("Error: Could not find metadata.tsv file")
        print("Tried paths:", [str(p) for p in possible_paths])
        sys.exit(1)

    # Read metadata
    df = pd.read_csv(metadata_path, sep='\t')

    # Check for required columns
    if 'family_name' not in df.columns or 'order_name' not in df.columns:
        print("Error: metadata must have 'family_name' and 'order_name' columns")
        sys.exit(1)

    # Get unique family-order combinations
    family_order = df[['family_name', 'order_name']].dropna().drop_duplicates()

    return family_order

def generate_family_ordering(family_order_df):
    """Generate family ordering grouped by order."""

    # Group by order
    grouped = family_order_df.groupby('order_name')['family_name'].apply(list).to_dict()

    # Sort orders alphabetically
    sorted_orders = sorted(grouped.keys())

    # Generate output lines
    lines = []
    lines.append("\n# Family entries grouped by order")
    lines.append("# Generated by scripts/generate_family_colors.py")

    for order in sorted_orders:
        # Sort families within order
        families = sorted(set(grouped[order]))

        # Add comment for this order group
        lines.append(f"\n# {order} families")

        # Add family entries
        for family in families:
            lines.append(f"family_name\t{family}")

    return lines

def append_to_color_ordering(lines):
    """Append family entries to color_ordering.tsv."""

    output_path = Path("defaults/color_ordering.tsv")

    if not output_path.exists():
        print(f"Error: {output_path} does not exist")
        sys.exit(1)

    # Read existing content to check if families already added
    with open(output_path, 'r') as f:
        existing_content = f.read()

    if "# Family entries grouped by order" in existing_content:
        print("Family entries already exist in color_ordering.tsv")
        response = input("Overwrite existing family entries? (y/n): ")
        if response.lower() != 'y':
            print("Aborted.")
            return

        # Remove existing family entries
        lines_list = existing_content.split('\n')
        cutoff_idx = None
        for i, line in enumerate(lines_list):
            if "# Family entries grouped by order" in line:
                cutoff_idx = i
                break

        if cutoff_idx is not None:
            existing_content = '\n'.join(lines_list[:cutoff_idx])
            # Remove trailing newlines
            existing_content = existing_content.rstrip()

    # Append new family entries
    with open(output_path, 'w') as f:
        f.write(existing_content)
        for line in lines:
            f.write(line + '\n')

    print(f"Successfully appended family entries to {output_path}")

def main():
    """Main function."""

    print("Generating family color ordering...")

    # Get family-order data from metadata
    family_order_df = get_family_order_data()

    print(f"Found {len(family_order_df)} unique family-order combinations")
    print(f"Orders: {sorted(family_order_df['order_name'].unique())}")

    # Generate ordering
    lines = generate_family_ordering(family_order_df)

    print(f"Generated {len(lines)} lines of ordering")

    # Append to color_ordering.tsv
    append_to_color_ordering(lines)

    print("Done!")

if __name__ == "__main__":
    main()